# Környezeti beállítások:

language: node_js
node_js:
  - "10"

sudo: false

# Figyelt branch:

branches:
  only:
  - main

# Cache engedélyezés node_modules -ra:

cache:
  directories:
    - node_modules

# Angular CLI biztosítása a deploy alatt:

before_script:
  - npm install -g @angular/cli

script:
  - echo "npm test temporarily disabled"
#  - ng lint
#  - ng test --watch=false --browsers=ChromeHeadlessNoSandbox

# Amennyiben nincsenek tesztek, úgy a "script" definiálására továbbra is szükség van (különben alapértelmezetten indul az npm test):

# script: echo "npm test temporarily disabled"

# Heroku - Travis-CI beállítások:

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  # API kulcs megadása Travis-CI felületén kerüljön hozzáadásra, ahol a változó neve: HEROKU_API_KEY értéke, pedig a Heroku UI-ban a projekt beállításai alatt található
  api-key: 
    secure: slRiT9om8RvMv0wNjQrQGvsI0rB9VjLJ9i+yQGLKCjyPBe7MGqZKdxQrMBYOAfLQd9RH1zvBJzAgXNat1vwcI98vGrMzsz+4NzOxTziKRFAJULWFvpSwXjRPFegjMT0IuaWC0h2A5/EAomVPbc/D1rBxhBBj5BSMV8ANRNBdqHmS7tDwHBmDvDs2P8OwBfSFQzUndSNeV/Nn9s5BHDbyIcKXVjsxzF0LRaaQovvgysedLYB6ODeXKixA7yAKgCh53ZJ6mx3RiqtGw+f4G2ZHTUZP6VJgg9GrSl2i2RFnbJsYHlS1lapYtOnuWIvCiEkLLDdtxAU/+49eC9xwTLoXuTcyEVjIIAl83FspXMPV8vx/JUX7SUv+HCo+Ii9JI1kKDlWjGElIVRSxSHLf4P8ORiJfIV0jrsPxLjqkkmKtfx7PNlrTi7vbWn461SSbZdd5xyinyF0fcEeUn+IEB3ZfZ/+PIJyiWeRmF4YhW5x7g/bO8BTsULsGYSpd90fDtwgMgubPaLcDHf+QPjGdwWNyL0EFy0N3sH+7w8JAgmKhOjP1XBk/auVH9v9CmCb+YzX43sdlxIlJce5DzidI3WUzBpzCMDTTVT7DxH5bCMp8UGvnJD1Fmry/BOSs7awQ1tzRXn3z+vJdcjgUExDTgN7xigMl6nCavqY6j9Dt1BQ1e2Q=
  app: munkahnyrk
  on: main
