# Környezeti beállítások:

language: node_js
node_js:
  - "10"

sudo: false

# Figyelt branch:

branches:
  only:
  - main

# Cache engedélyezés node_modules -ra:

cache:
  directories:
    - node_modules

# Angular CLI biztosítása a deploy alatt:

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng test --watch=false --browsers=ChromeHeadlessNoSandbox

# Amennyiben nincsenek tesztek, úgy a "script" definiálására továbbra is szükség van (különben alapértelmezetten indul az npm test):

# script: echo "npm test temporarily disabled"

# Heroku - Travis-CI beállítások:

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  # API kulcs megadása Travis-CI felületén kerüljön hozzáadásra, ahol a változó neve: HEROKU_API_KEY értéke, pedig a Heroku UI-ban a projekt beállításai alatt található
  api-key: 
    secure:"kVFPZD2wel/fMRUU5C4XihP1jUm9ztCdQ6KxzrvCUUAnMKLht/YFGxzECRVe0sYd49DO88O+CdHRMTc9w+uPukuCr7zE+F2X0KD4q5Ov98hhNKGA9Wb5JVaSuIXINvaJn07y7dN+pnyWslR6siCFtW2A6wAU7/Rjv9gUuu0psOIc4MUhKDl1754Z6QPJoj8wnkqvd7j1KUiFTSpnlJYr0lwAkY1Yo96INnxlTvE32UczxxZ6y7KrrfFGjj4mRFcrFAe0u6rhDKCcdK/vY8eslFaPL9W911NDH8kkDJiPFH+Wa7UAGf+PhkXBglSF8j5NYjPvJwgXvq/R6j/62qvBFyzbqpd0uSKvd1qVHkFoFBfkxuYGBEXE6GSBM4aGabBhnE0PYIwG4h7DuPgqh/TIPsaZ30ElUmdqFTuA9bnYLHFMaI3y76YRp1EEjRcez+r3s4oHuII2QmhXzcz2rKdxKHOiJwHSR+6qE7QoHdLKkqAmcevvJ4D8vkmeuz7CFBuhY+tS4m+omGn4t6jZ5JGABeu7TAOUTOrjGomNv5K/8ODYy6E2vYRETKirVIuiq3Ztxgezrw0Za0pVGOfVe5It7/q7/Izmrs4EDBG2LY5SyhG9IoOk6MkUOKh6VePrBaJ2bMpDO/qhJs7pGWwOQB5xjQojquW5NJ/Mu9xVaFTp/F4="
  app: munkahnyrk
  on:
    brach: main
